package org.example.controller;

public enum SignInStatus {
    SIGN_IN_SUCCESSFUL,
    EMPTY_FIELD,
    INVALID_EMAIL,
    INVALID_NRC,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    STRONG_PASSWORD,
    PASSWORD_TOO_SHORT,
    PASSWORD_MISSING_UPPERCASE_CHARACTER,
    PASSWORD_MISSING_LOWERCASE_CHARACTER,
    PASSWORD_MISSING_DIGITS,
    PASSWORD_MISSING_SPECIAL_CHARACTERS
}
